firstname: Foued,Beligh
spring:
  profiles: default
  cloud:
    config:
      uri: http://localhost:8001
---
spring:
  profiles: other
  cloud:
    config:
      uri: http://localhost:8001
firstname: jack,tony


